{
 "title": "Analytics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top days by orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date, orders_count FROM mart.daily_revenue ORDER BY orders_count DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Daily revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date, revenue\r\nFROM mart.daily_revenue\r\nORDER BY date;"
    }
   ]
  },
  {
   "title": "Conversion rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT date, conversion_rate\r\nFROM mart.conversion\r\nORDER BY date;"
    }
   ]
  },
  {
   "title": "Cohort LTV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT cohort_month, order_month, revenue FROM mart.cohort_ltv ORDER BY 1, 2;"
    }
   ]
  }
 ]
}