{
 "title": "Analytics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Best Order Days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date, orders_count\r\nFROM mart.daily_revenue\r\nORDER BY orders_count DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Daily Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date, revenue\r\nFROM mart.daily_revenue\r\nORDER BY date;"
    }
   ]
  },
  {
   "title": "Conversion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT date, conversion_rate\r\nFROM mart.conversion\r\nORDER BY date;"
    }
   ]
  }
 ]
}