// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.ecommerce
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class EcommerceEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""EcommerceEvent"",""namespace"":""com.ecommerce"",""fields"":[{""name"":""event_type"",""type"":""string""},{""name"":""user_id"",""type"":""string""},{""name"":""payload"",""doc"":""JSON string — different structure per event type"",""type"":""string""},{""name"":""created_at"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		private string _event_type;
		private string _user_id;
		/// <summary>
		/// JSON string — different structure per event type
		/// </summary>
		private string _payload;
		private System.DateTime _created_at;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return EcommerceEvent._SCHEMA;
			}
		}
		public string event_type
		{
			get
			{
				return this._event_type;
			}
			set
			{
				this._event_type = value;
			}
		}
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				this._user_id = value;
			}
		}
		/// <summary>
		/// JSON string — different structure per event type
		/// </summary>
		public string payload
		{
			get
			{
				return this._payload;
			}
			set
			{
				this._payload = value;
			}
		}
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				this._created_at = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.event_type;
			case 1: return this.user_id;
			case 2: return this.payload;
			case 3: return this.created_at;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.event_type = (System.String)fieldValue; break;
			case 1: this.user_id = (System.String)fieldValue; break;
			case 2: this.payload = (System.String)fieldValue; break;
			case 3: this.created_at = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
